import book from "../assets/images/book_image.png";
import book2 from "../assets/images/book_image2.png";
export const allBooks = [
  {
    title: "The lion king",
    author: "Monroe Monroe",
    category: "Thriller",
    id: 1,
    imageUrl: book,
  },
  {
    title: "The awesome monkey",
    author: "Monroe Monroe",
    category: "Comedy",
    id: 2,
    imageUrl: book,
  },
  {
    title: "Going south",
    author: "Monroe Monroe",
    category: "Romance",
    id: 3,
    imageUrl: book,
  },
  {
    title: "Head to Head",
    author: "Monroe Monroe",
    category: "Adventure",
    id: 4,
    imageUrl: book,
  },
  {
    title: "Alabama paperback",
    author: "Monroe Monroe",
    category: "Thriller",
    id: 5,
    imageUrl: book,
  },
  {
    title: "Just as heard",
    author: "Monroe Monroe",
    category: "Fantasy",
    id: 6,
    imageUrl: book,
  },
  {
    title: "Incoming",
    author: "Monroe Monroe",
    category: "Comedy",
    id: 7,
    imageUrl: book,
  },
  {
    title: "Something nice",
    author: "Monroe Monroe",
    category: "Romance",
    id: 8,
    imageUrl: book,
  },
  {
    title: "Halelluyah",
    author: "Monroe Monroe",
    category: "Religion",
    id: 9,
    imageUrl: book,
  },
  {
    title: "The wonders",
    author: "Monroe Monroe",
    category: "Religion",
    id: 10,
    imageUrl: book,
  },
  {
    title: "Make believe",
    author: "Monroe Monroe",
    category: "Fantasy",
    id: 11,
    imageUrl: book,
  },
  {
    title: "A blue moon",
    author: "Monroe Monroe",
    category: "Romance",
    id: 12,
    imageUrl: book,
  },
];
export const recentBooks = [
  {
    title: "The lion king",
    author: "Monroe Monroe",
    category: "Thriller",
    id: 1,
    imageUrl: book2,
  },
  {
    title: "The awesome monkey",
    author: "Monroe Monroe",
    category: "Comedy",
    id: 2,
    imageUrl: book2,
  },
  {
    title: "Going south",
    author: "Monroe Monroe",
    category: "Romance",
    id: 3,
    imageUrl: book2,
  },
  {
    title: "Head to Head",
    author: "Monroe Monroe",
    category: "Adventure",
    id: 4,
    imageUrl: book2,
  },
  {
    title: "Alabama paperback",
    author: "Monroe Monroe",
    category: "Thriller",
    id: 5,
    imageUrl: book2,
  },
  {
    title: "Just as heard",
    author: "Monroe Monroe",
    category: "Fantasy",
    id: 6,
    imageUrl: book2,
  },
  {
    title: "Incoming",
    author: "Monroe Monroe",
    category: "Comedy",
    id: 7,
    imageUrl: book2,
  },
  {
    title: "Something nice",
    author: "Monroe Monroe",
    category: "Romance",
    id: 8,
    imageUrl: book2,
  },
  {
    title: "Halelluyah",
    author: "Monroe Monroe",
    category: "Religion",
    id: 9,
    imageUrl: book2,
  },
  {
    title: "The wonders",
    author: "Monroe Monroe",
    category: "Religion",
    id: 10,
    imageUrl: book2,
  },
  {
    title: "Make believe",
    author: "Monroe Monroe",
    category: "Fantasy",
    id: 11,
    imageUrl: book2,
  },
  {
    title: "A blue moon",
    author: "Monroe Monroe",
    category: "Romance",
    id: 12,
    imageUrl: book2,
  },
];
export const categories = [
  "Romance",
  "Biography",
  "Adventure",
  "Comedy",
  "Fantasy",
  "Thriller",
  "Religion",
  "Food/Recipes",
  "Health",
  "Tech",
  "History",
];
